apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-toolkit.fullname" . }}-litellm
  labels:
    {{- include "ai-toolkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
spec:
  type: {{ .Values.litellm.service.type }}
  ports:
    - port: {{ .Values.litellm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-toolkit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
