{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-toolkit.fullname" . }}-postgresql-initdb
  labels:
    {{- include "ai-toolkit.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  init_db.sh: |
{{ .Values.postgresql.initdbScript | indent 4 }}
{{- end }}
